import type { Lang } from "./i18n";

/** Landing chrome. Prices stay in the catalog — never hard-code them here. */
export const LANDING_COPY: Record<Lang, Record<string, string>> = {
  en: {
    "Practice with hints. Test with none.": "Practice with hints. Test with none.",
    "Enter the gym": "Enter the gym",
    "Open now": "Open now",
    "Strict book-move trainer": "Strict book-move trainer",
    "Drill packs": "Drill packs",
    "Opening drill packs": "Opening drill packs",
    "Chess opening drills available now": "Chess opening drills available now",
    Site: "Site",
    Support: "Support",
    "Log in": "Log in",
    Theme: "Theme",
    "{n} free · {price}": "{n} free · {price}",
    "Chess opening lessons": "Chess opening lessons",
    "{n} lessons": "{n} lessons",
  },
  es: {
    "Practice with hints. Test with none.": "Practica con pistas. El test, sin ninguna.",
    "Enter the gym": "Entra al gimnasio",
    "Open now": "Abierto ahora",
    "Strict book-move trainer": "Entrenador estricto de jugadas de libro",
    "Drill packs": "Paquetes de ejercicios",
    "Opening drill packs": "Paquetes de ejercicios de apertura",
    "Chess opening drills available now": "Ejercicios de aperturas de ajedrez disponibles ahora",
    Site: "Sitio",
    Support: "Soporte",
    "Log in": "Entrar",
    Theme: "Tema",
    "{n} free · {price}": "{n} gratis · {price}",
    "Chess opening lessons": "Lecciones de aperturas",
    "{n} lessons": "{n} lecciones",
  },
  zh: {
    "Practice with hints. Test with none.": "练习有提示。测验没有。",
    "Enter the gym": "进入训练馆",
    "Open now": "现已开放",
    "Strict book-move trainer": "严格的书谱走法训练",
    "Drill packs": "训练包",
    "Opening drill packs": "开局训练包",
    "Chess opening drills available now": "国际象棋开局训练现已提供",
    Site: "网站",
    Support: "支持",
    "Log in": "登录",
    Theme: "主题",
    "{n} free · {price}": "{n} 免费 · {price}",
    "Chess opening lessons": "国际象棋开局课",
    "{n} lessons": "{n} 节课",
  },
  fr: {
    "Practice with hints. Test with none.": "Entraîne-toi avec des indices. Le test, sans aucun.",
    "Enter the gym": "Entre dans la salle",
    "Open now": "Ouvert maintenant",
    "Strict book-move trainer": "Entraîneur strict aux coups du livre",
    "Drill packs": "Packs d'exercices",
    "Opening drill packs": "Packs d'exercices d'ouverture",
    "Chess opening drills available now": "Exercices d'ouvertures d'échecs disponibles maintenant",
    Site: "Site",
    Support: "Assistance",
    "Log in": "Connexion",
    Theme: "Thème",
    "{n} free · {price}": "{n} gratuit · {price}",
    "Chess opening lessons": "Leçons d'ouvertures",
    "{n} lessons": "{n} leçons",
  },
  de: {
    "Practice with hints. Test with none.": "Üben mit Hinweisen. Testen ohne.",
    "Enter the gym": "In die Halle",
    "Open now": "Jetzt offen",
    "Strict book-move trainer": "Strenger Buchzug-Trainer",
    "Drill packs": "Übungspakete",
    "Opening drill packs": "Eröffnungs-Übungspakete",
    "Chess opening drills available now": "Schacheröffnungsübungen jetzt verfügbar",
    Site: "Website",
    Support: "Hilfe",
    "Log in": "Anmelden",
    Theme: "Design",
    "{n} free · {price}": "{n} gratis · {price}",
    "Chess opening lessons": "Schacheröffnungslektionen",
    "{n} lessons": "{n} Lektionen",
  },
  pt: {
    "Practice with hints. Test with none.": "Pratica com dicas. O teste, sem nenhuma.",
    "Enter the gym": "Entra no ginásio",
    "Open now": "Aberto agora",
    "Strict book-move trainer": "Treinador estrito de lances de livro",
    "Drill packs": "Pacotes de exercícios",
    "Opening drill packs": "Pacotes de exercícios de abertura",
    "Chess opening drills available now": "Exercícios de aberturas de xadrez disponíveis agora",
    Site: "Site",
    Support: "Suporte",
    "Log in": "Entrar",
    Theme: "Tema",
    "{n} free · {price}": "{n} grátis · {price}",
    "Chess opening lessons": "Lições de aberturas",
    "{n} lessons": "{n} lições",
  },
  ru: {
    "Practice with hints. Test with none.": "Тренировка с подсказками. Тест без них.",
    "Enter the gym": "Войти в зал",
    "Open now": "Уже открыто",
    "Strict book-move trainer": "Строгий тренажёр книжных ходов",
    "Drill packs": "Тренировочные пакеты",
    "Opening drill packs": "Пакеты дебютных тренировок",
    "Chess opening drills available now": "Тренировки шахматных дебютов уже доступны",
    Site: "Сайт",
    Support: "Поддержка",
    "Log in": "Войти",
    Theme: "Тема",
    "{n} free · {price}": "{n} бесплатно · {price}",
    "Chess opening lessons": "Уроки дебютов",
    "{n} lessons": "{n} урока",
  },
  it: {
    "Practice with hints. Test with none.": "Allenati con i suggerimenti. Il test, senza.",
    "Enter the gym": "Entra in palestra",
    "Open now": "Aperto ora",
    "Strict book-move trainer": "Allenatore rigoroso delle mosse di libro",
    "Drill packs": "Pacchetti di esercizi",
    "Opening drill packs": "Pacchetti di esercizi sulle aperture",
    "Chess opening drills available now": "Esercizi sulle aperture degli scacchi disponibili ora",
    Site: "Sito",
    Support: "Supporto",
    "Log in": "Accedi",
    Theme: "Tema",
    "{n} free · {price}": "{n} gratis · {price}",
    "Chess opening lessons": "Lezioni di aperture",
    "{n} lessons": "{n} lezioni",
  },
  hi: {
    "Practice with hints. Test with none.": "अभ्यास संकेतों के साथ। परीक्षा बिना।",
    "Enter the gym": "जिम में प्रवेश",
    "Open now": "अभी खुला",
    "Strict book-move trainer": "सख्त बुक-मूव ट्रेनर",
    "Drill packs": "ड्रिल पैक",
    "Opening drill packs": "ओपनिंग ड्रिल पैक",
    "Chess opening drills available now": "शतरंज ओपनिंग ड्रिल अभी उपलब्ध",
    Site: "साइट",
    Support: "सहायता",
    "Log in": "लॉग इन",
    Theme: "थीम",
    "{n} free · {price}": "{n} मुफ़्त · {price}",
    "Chess opening lessons": "शतरंज ओपनिंग पाठ",
    "{n} lessons": "{n} पाठ",
  },
  ja: {
    "Practice with hints. Test with none.": "ヒントありで練習。テストはヒントなし。",
    "Enter the gym": "ジムに入る",
    "Open now": "公開中",
    "Strict book-move trainer": "厳密な定跡トレーナー",
    "Drill packs": "ドリルパック",
    "Opening drill packs": "オープニングのドリルパック",
    "Chess opening drills available now": "チェスのオープニングドリルが公開中",
    Site: "サイト",
    Support: "サポート",
    "Log in": "ログイン",
    Theme: "テーマ",
    "{n} free · {price}": "{n} 無料 · {price}",
    "Chess opening lessons": "チェスオープニング講座",
    "{n} lessons": "{n} レッスン",
  },
  ar: {
    "Practice with hints. Test with none.": "تدرّب مع تلميحات. الاختبار بلا تلميح.",
    "Enter the gym": "ادخل الصالة",
    "Open now": "مفتوح الآن",
    "Strict book-move trainer": "مدرّب صارم لنقلات الكتاب",
    "Drill packs": "حزم التمارين",
    "Opening drill packs": "حزم تمارين الافتتاح",
    "Chess opening drills available now": "تمارين افتتاحيات الشطرنج متاحة الآن",
    Site: "الموقع",
    Support: "الدعم",
    "Log in": "تسجيل الدخول",
    Theme: "المظهر",
    "{n} free · {price}": "{n} مجانًا · {price}",
    "Chess opening lessons": "دروس افتتاحيات الشطرنج",
    "{n} lessons": "{n} دروس",
  },
  tr: {
    "Practice with hints. Test with none.": "İpuçlarıyla çalış. Testte hiçbiri yok.",
    "Enter the gym": "Salona gir",
    "Open now": "Şimdi açık",
    "Strict book-move trainer": "Katı kitap-hamlesi antrenörü",
    "Drill packs": "Alıştırma paketleri",
    "Opening drill packs": "Açılış alıştırma paketleri",
    "Chess opening drills available now": "Satranç açılış alıştırmaları şimdi hazır",
    Site: "Site",
    Support: "Destek",
    "Log in": "Giriş yap",
    Theme: "Tema",
    "{n} free · {price}": "{n} ücretsiz · {price}",
    "Chess opening lessons": "Satranç açılış dersleri",
    "{n} lessons": "{n} ders",
  },
};
