import type { Lang } from "./i18n";

/** Landing chrome. Prices stay in the catalog — never hard-code them here. */
export const LANDING_COPY: Record<Lang, Record<string, string>> = {
  en: {
    "Practice with hints. Test with none.": "Practice with hints. Test with none.",
    "Enter the gym": "Enter the gym",
    "Open now": "Open now",
    "Study first. Then test yourself from memory":
      "Study first. Then test yourself from memory",
    "Please leave feedback for openings you’d like to see":
      "Please leave feedback for openings you’d like to see",
    "Drill packs": "Drill packs",
    "Opening drill packs": "Opening drill packs",
    "Chess opening packs available now": "Chess opening packs available now",
    Site: "Site",
    Support: "Support",
    "Log in": "Log in",
    Theme: "Theme",
    "{n} free · {price}": "{n} free · {price}",
    "{price} unlocks the whole pack": "{price} unlocks the whole pack",
    "Whole pack · {price}": "Whole pack · {price}",
    "Whole pack · {price} — all {n} lines": "Whole pack · {price} — all {n} lines",
    "{n} free · {price} unlocks the whole pack": "{n} free · {price} unlocks the whole pack",
    "Chess opening lessons": "Chess opening lessons",
    "{n} lessons": "{n} lessons",
    "Scotch Gambit Lessons": "Scotch Gambit Lessons",
    "Separate from drill packs. Buy all does not include lessons.":
      "Separate from drill packs. Buy all does not include lessons.",
    "Lesson 1 is free": "Lesson 1 is free",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.",
    "Unlock the remaining lessons": "Unlock the remaining lessons",
    "Back to lessons": "Back to lessons",
  },
  es: {
    "Practice with hints. Test with none.": "Practica con pistas. El test, sin ninguna.",
    "Enter the gym": "Entra al gimnasio",
    "Open now": "Abierto ahora",
    "Study first. Then test yourself from memory":
      "Estudia primero. Luego ponte a prueba de memoria",
    "Please leave feedback for openings you’d like to see":
      "Deja un comentario sobre las aperturas que te gustaría ver",
    "Drill packs": "Paquetes de ejercicios",
    "Opening drill packs": "Paquetes de ejercicios de apertura",
    "Chess opening packs available now": "Paquetes de aperturas de ajedrez disponibles ahora",
    Site: "Sitio",
    Support: "Soporte",
    "Log in": "Entrar",
    Theme: "Tema",
    "{n} free · {price}": "{n} gratis · {price}",
    "{price} unlocks the whole pack": "{price} desbloquea el pack entero",
    "Whole pack · {price}": "Pack entero · {price}",
    "Whole pack · {price} — all {n} lines": "Pack entero · {price} — las {n} líneas",
    "{n} free · {price} unlocks the whole pack": "{n} gratis · {price} desbloquea el pack entero",
    "Chess opening lessons": "Lecciones de aperturas",
    "{n} lessons": "{n} lecciones",
    "Scotch Gambit Lessons": "Lecciones del Scotch Gambit",
    "Separate from drill packs. Buy all does not include lessons.":
      "Aparte de los packs de ejercicios. Comprar todo no incluye las lecciones.",
    "Lesson 1 is free": "La lección 1 es gratis",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "Las lecciones 2 y 3 cuestan {price}. Una compra de lecciones aparte: no es un pack de ejercicios, y Comprar todo no las incluye.",
    "Unlock the remaining lessons": "Desbloquear las lecciones restantes",
    "Back to lessons": "Volver a las lecciones",
  },
  zh: {
    "Practice with hints. Test with none.": "练习有提示。测验没有。",
    "Enter the gym": "进入训练馆",
    "Open now": "现已开放",
    "Study first. Then test yourself from memory": "先学。再凭记忆自测",
    "Please leave feedback for openings you’d like to see":
      "请留下反馈，告诉我们你想看到的开局",
    "Drill packs": "训练包",
    "Opening drill packs": "开局训练包",
    "Chess opening packs available now": "国际象棋开局课程包现已提供",
    Site: "网站",
    Support: "支持",
    "Log in": "登录",
    Theme: "主题",
    "{n} free · {price}": "{n} 免费 · {price}",
    "{price} unlocks the whole pack": "{price} 解锁整个棋包",
    "Whole pack · {price}": "整包 · {price}",
    "Whole pack · {price} — all {n} lines": "整包 · {price} — 全部 {n} 条线路",
    "{n} free · {price} unlocks the whole pack": "{n} 免费 · {price} 解锁整个棋包",
    "Chess opening lessons": "国际象棋开局课",
    "{n} lessons": "{n} 节课",
    "Scotch Gambit Lessons": "Scotch Gambit 课程",
    "Separate from drill packs. Buy all does not include lessons.":
      "与训练包分开。全部购买不含课程。",
    "Lesson 1 is free": "第 1 课免费",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "第 2 课和第 3 课为 {price}。这是单独的课程购买，不属于训练包，全部购买也不包含。",
    "Unlock the remaining lessons": "解锁其余课程",
    "Back to lessons": "返回课程",
  },
  fr: {
    "Practice with hints. Test with none.": "Entraîne-toi avec des indices. Le test, sans aucun.",
    "Enter the gym": "Entre dans la salle",
    "Open now": "Ouvert maintenant",
    "Study first. Then test yourself from memory":
      "Étudie d’abord. Puis teste-toi de mémoire",
    "Please leave feedback for openings you’d like to see":
      "Laisse un retour sur les ouvertures que tu aimerais voir",
    "Drill packs": "Packs d'exercices",
    "Opening drill packs": "Packs d'exercices d'ouverture",
    "Chess opening packs available now": "Packs d'ouvertures d'échecs disponibles maintenant",
    Site: "Site",
    Support: "Assistance",
    "Log in": "Connexion",
    Theme: "Thème",
    "{n} free · {price}": "{n} gratuit · {price}",
    "{price} unlocks the whole pack": "{price} débloque le pack entier",
    "Whole pack · {price}": "Pack entier · {price}",
    "Whole pack · {price} — all {n} lines": "Pack entier · {price} — les {n} lignes",
    "{n} free · {price} unlocks the whole pack": "{n} gratuit · {price} débloque le pack entier",
    "Chess opening lessons": "Leçons d'ouvertures",
    "{n} lessons": "{n} leçons",
    "Scotch Gambit Lessons": "Leçons du Scotch Gambit",
    "Separate from drill packs. Buy all does not include lessons.":
      "À part des packs d'exercices. Tout acheter n'inclut pas les leçons.",
    "Lesson 1 is free": "La leçon 1 est gratuite",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "Les leçons 2 et 3 coûtent {price}. Un achat de leçons à part — pas un pack d'exercices, et pas inclus dans Tout acheter.",
    "Unlock the remaining lessons": "Débloquer les leçons restantes",
    "Back to lessons": "Retour aux leçons",
  },
  de: {
    "Practice with hints. Test with none.": "Üben mit Hinweisen. Testen ohne.",
    "Enter the gym": "In die Halle",
    "Open now": "Jetzt offen",
    "Study first. Then test yourself from memory":
      "Erst lernen. Dann aus dem Gedächtnis prüfen",
    "Please leave feedback for openings you’d like to see":
      "Hinterlasse Feedback zu Eröffnungen, die du sehen möchtest",
    "Drill packs": "Übungspakete",
    "Opening drill packs": "Eröffnungs-Übungspakete",
    "Chess opening packs available now": "Schacheröffnungspakete jetzt verfügbar",
    Site: "Website",
    Support: "Hilfe",
    "Log in": "Anmelden",
    Theme: "Design",
    "{n} free · {price}": "{n} gratis · {price}",
    "{price} unlocks the whole pack": "{price} schaltet das ganze Pack frei",
    "Whole pack · {price}": "Ganzes Pack · {price}",
    "Whole pack · {price} — all {n} lines": "Ganzes Pack · {price} — alle {n} Linien",
    "{n} free · {price} unlocks the whole pack": "{n} gratis · {price} schaltet das ganze Pack frei",
    "Chess opening lessons": "Schacheröffnungslektionen",
    "{n} lessons": "{n} Lektionen",
    "Scotch Gambit Lessons": "Scotch-Gambit-Lektionen",
    "Separate from drill packs. Buy all does not include lessons.":
      "Getrennt von den Übungspaketen. Alles kaufen enthält keine Lektionen.",
    "Lesson 1 is free": "Lektion 1 ist kostenlos",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "Lektionen 2 und 3 kosten {price}. Ein eigener Lektionskauf — kein Übungspaket, und nicht in Alles kaufen enthalten.",
    "Unlock the remaining lessons": "Die übrigen Lektionen freischalten",
    "Back to lessons": "Zurück zu den Lektionen",
  },
  pt: {
    "Practice with hints. Test with none.": "Pratica com dicas. O teste, sem nenhuma.",
    "Enter the gym": "Entra no ginásio",
    "Open now": "Aberto agora",
    "Study first. Then test yourself from memory":
      "Estuda primeiro. Depois testa-te de memória",
    "Please leave feedback for openings you’d like to see":
      "Deixa feedback sobre as aberturas que gostarias de ver",
    "Drill packs": "Pacotes de exercícios",
    "Opening drill packs": "Pacotes de exercícios de abertura",
    "Chess opening packs available now": "Pacotes de aberturas de xadrez disponíveis agora",
    Site: "Site",
    Support: "Suporte",
    "Log in": "Entrar",
    Theme: "Tema",
    "{n} free · {price}": "{n} grátis · {price}",
    "{price} unlocks the whole pack": "{price} desbloqueia o pack inteiro",
    "Whole pack · {price}": "Pack inteiro · {price}",
    "Whole pack · {price} — all {n} lines": "Pack inteiro · {price} — as {n} linhas",
    "{n} free · {price} unlocks the whole pack": "{n} grátis · {price} desbloqueia o pack inteiro",
    "Chess opening lessons": "Lições de aberturas",
    "{n} lessons": "{n} lições",
    "Scotch Gambit Lessons": "Lições do Scotch Gambit",
    "Separate from drill packs. Buy all does not include lessons.":
      "À parte dos packs de exercícios. Comprar tudo não inclui as lições.",
    "Lesson 1 is free": "A lição 1 é grátis",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "As lições 2 e 3 custam {price}. Uma compra de lições à parte — não é um pack de exercícios, e Comprar tudo não as inclui.",
    "Unlock the remaining lessons": "Desbloquear as lições restantes",
    "Back to lessons": "Voltar às lições",
  },
  ru: {
    "Practice with hints. Test with none.": "Тренировка с подсказками. Тест без них.",
    "Enter the gym": "Войти в зал",
    "Open now": "Уже открыто",
    "Study first. Then test yourself from memory":
      "Сначала учи. Потом проверь себя по памяти",
    "Please leave feedback for openings you’d like to see":
      "Оставьте отзыв о дебютах, которые хотите увидеть",
    "Drill packs": "Тренировочные пакеты",
    "Opening drill packs": "Пакеты дебютных тренировок",
    "Chess opening packs available now": "Пакеты шахматных дебютов уже доступны",
    Site: "Сайт",
    Support: "Поддержка",
    "Log in": "Войти",
    Theme: "Тема",
    "{n} free · {price}": "{n} бесплатно · {price}",
    "{price} unlocks the whole pack": "{price} открывает весь пак",
    "Whole pack · {price}": "Весь пак · {price}",
    "Whole pack · {price} — all {n} lines": "Весь пак · {price} — все {n} линий",
    "{n} free · {price} unlocks the whole pack": "{n} бесплатно · {price} открывает весь пак",
    "Chess opening lessons": "Уроки дебютов",
    "{n} lessons": "{n} урока",
    "Scotch Gambit Lessons": "Уроки Scotch Gambit",
    "Separate from drill packs. Buy all does not include lessons.":
      "Отдельно от тренировочных паков. «Купить всё» не включает уроки.",
    "Lesson 1 is free": "Урок 1 бесплатный",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "Уроки 2 и 3 стоят {price}. Отдельная покупка уроков — не тренировочный пак, и «Купить всё» их не включает.",
    "Unlock the remaining lessons": "Открыть остальные уроки",
    "Back to lessons": "Назад к урокам",
  },
  it: {
    "Practice with hints. Test with none.": "Allenati con i suggerimenti. Il test, senza.",
    "Enter the gym": "Entra in palestra",
    "Open now": "Aperto ora",
    "Study first. Then test yourself from memory":
      "Prima studia. Poi mettiti alla prova a memoria",
    "Please leave feedback for openings you’d like to see":
      "Lascia un feedback sulle aperture che vorresti vedere",
    "Drill packs": "Pacchetti di esercizi",
    "Opening drill packs": "Pacchetti di esercizi sulle aperture",
    "Chess opening packs available now": "Pacchetti di aperture degli scacchi disponibili ora",
    Site: "Sito",
    Support: "Supporto",
    "Log in": "Accedi",
    Theme: "Tema",
    "{n} free · {price}": "{n} gratis · {price}",
    "{price} unlocks the whole pack": "{price} sblocca l'intero pack",
    "Whole pack · {price}": "Pack intero · {price}",
    "Whole pack · {price} — all {n} lines": "Pack intero · {price} — tutte le {n} linee",
    "{n} free · {price} unlocks the whole pack": "{n} gratis · {price} sblocca l'intero pack",
    "Chess opening lessons": "Lezioni di aperture",
    "{n} lessons": "{n} lezioni",
    "Scotch Gambit Lessons": "Lezioni della Scotch Gambit",
    "Separate from drill packs. Buy all does not include lessons.":
      "Separate dai pack di esercizi. Acquista tutto non include le lezioni.",
    "Lesson 1 is free": "La lezione 1 è gratis",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "Le lezioni 2 e 3 costano {price}. Un acquisto di lezioni a parte — non un pack di esercizi, e non incluso in Acquista tutto.",
    "Unlock the remaining lessons": "Sblocca le lezioni rimanenti",
    "Back to lessons": "Torna alle lezioni",
  },
  hi: {
    "Practice with hints. Test with none.": "अभ्यास संकेतों के साथ। परीक्षा बिना।",
    "Enter the gym": "जिम में प्रवेश",
    "Open now": "अभी खुला",
    "Study first. Then test yourself from memory":
      "पहले पढ़ो। फिर याद से खुद को परखो",
    "Please leave feedback for openings you’d like to see":
      "जो ओपनिंग आप देखना चाहते हैं, उनके लिए प्रतिक्रिया छोड़ें",
    "Drill packs": "ड्रिल पैक",
    "Opening drill packs": "ओपनिंग ड्रिल पैक",
    "Chess opening packs available now": "शतरंज ओपनिंग पैक अभी उपलब्ध",
    Site: "साइट",
    Support: "सहायता",
    "Log in": "लॉग इन",
    Theme: "थीम",
    "{n} free · {price}": "{n} मुफ़्त · {price}",
    "{price} unlocks the whole pack": "{price} पूरा पैक खोलता है",
    "Whole pack · {price}": "पूरा पैक · {price}",
    "Whole pack · {price} — all {n} lines": "पूरा पैक · {price} — सभी {n} लाइनें",
    "{n} free · {price} unlocks the whole pack": "{n} मुफ़्त · {price} पूरा पैक खोलता है",
    "Chess opening lessons": "शतरंज ओपनिंग पाठ",
    "{n} lessons": "{n} पाठ",
    "Scotch Gambit Lessons": "Scotch Gambit पाठ",
    "Separate from drill packs. Buy all does not include lessons.":
      "ड्रिल पैक से अलग। सब खरीदें में पाठ शामिल नहीं।",
    "Lesson 1 is free": "पाठ 1 मुफ़्त है",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "पाठ 2 और 3 की कीमत {price} है। यह अलग पाठ खरीद है — ड्रिल पैक का हिस्सा नहीं, और सब खरीदें में शामिल नहीं।",
    "Unlock the remaining lessons": "बाकी पाठ खोलें",
    "Back to lessons": "पाठों पर वापस",
  },
  ja: {
    "Practice with hints. Test with none.": "ヒントありで練習。テストはヒントなし。",
    "Enter the gym": "ジムに入る",
    "Open now": "公開中",
    "Study first. Then test yourself from memory":
      "まず学ぶ。それから記憶で自分を試す",
    "Please leave feedback for openings you’d like to see":
      "見てほしいオープニングがあれば、フィードバックを残してください",
    "Drill packs": "ドリルパック",
    "Opening drill packs": "オープニングのドリルパック",
    "Chess opening packs available now": "チェスのオープニングパックが公開中",
    Site: "サイト",
    Support: "サポート",
    "Log in": "ログイン",
    Theme: "テーマ",
    "{n} free · {price}": "{n} 無料 · {price}",
    "{price} unlocks the whole pack": "{price} でパック全体を解除",
    "Whole pack · {price}": "パック全体 · {price}",
    "Whole pack · {price} — all {n} lines": "パック全体 · {price} — 全 {n} ライン",
    "{n} free · {price} unlocks the whole pack": "{n} 無料 · {price} でパック全体を解除",
    "Chess opening lessons": "チェスオープニング講座",
    "{n} lessons": "{n} レッスン",
    "Scotch Gambit Lessons": "Scotch Gambit のレッスン",
    "Separate from drill packs. Buy all does not include lessons.":
      "ドリルパックとは別です。全部購入にレッスンは含まれません。",
    "Lesson 1 is free": "レッスン 1 は無料",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "レッスン 2 と 3 は {price} です。レッスンだけの購入で、ドリルパックではなく、全部購入にも含まれません。",
    "Unlock the remaining lessons": "残りのレッスンを解除",
    "Back to lessons": "レッスンに戻る",
  },
  ar: {
    "Practice with hints. Test with none.": "تدرّب مع تلميحات. الاختبار بلا تلميح.",
    "Enter the gym": "ادخل الصالة",
    "Open now": "مفتوح الآن",
    "Study first. Then test yourself from memory":
      "ادرس أولاً. ثم اختبر نفسك من الذاكرة",
    "Please leave feedback for openings you’d like to see":
      "اترك ملاحظات عن الافتتاحيات التي تودّ رؤيتها",
    "Drill packs": "حزم التمارين",
    "Opening drill packs": "حزم تمارين الافتتاح",
    "Chess opening packs available now": "حزم افتتاحيات الشطرنج متاحة الآن",
    Site: "الموقع",
    Support: "الدعم",
    "Log in": "تسجيل الدخول",
    Theme: "المظهر",
    "{n} free · {price}": "{n} مجانًا · {price}",
    "{price} unlocks the whole pack": "{price} يفتح الحزمة كاملة",
    "Whole pack · {price}": "الحزمة كاملة · {price}",
    "Whole pack · {price} — all {n} lines": "الحزمة كاملة · {price} — كل الخطوط ({n})",
    "{n} free · {price} unlocks the whole pack": "{n} مجانًا · {price} يفتح الحزمة كاملة",
    "Chess opening lessons": "دروس افتتاحيات الشطرنج",
    "{n} lessons": "{n} دروس",
    "Scotch Gambit Lessons": "دروس Scotch Gambit",
    "Separate from drill packs. Buy all does not include lessons.":
      "منفصلة عن حزم التمارين. شراء الكل لا يشمل الدروس.",
    "Lesson 1 is free": "الدرس 1 مجاني",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "الدرسان 2 و3 بسعر {price}. شراء دروس منفصل — ليس جزءًا من حزمة تمارين، وشراء الكل لا يشملها.",
    "Unlock the remaining lessons": "فتح بقية الدروس",
    "Back to lessons": "العودة إلى الدروس",
  },
  tr: {
    "Practice with hints. Test with none.": "İpuçlarıyla çalış. Testte hiçbiri yok.",
    "Enter the gym": "Salona gir",
    "Open now": "Şimdi açık",
    "Study first. Then test yourself from memory":
      "Önce çalış. Sonra hafızandan kendini sına",
    "Please leave feedback for openings you’d like to see":
      "Görmek istediğin açılışlar için geri bildirim bırak",
    "Drill packs": "Alıştırma paketleri",
    "Opening drill packs": "Açılış alıştırma paketleri",
    "Chess opening packs available now": "Satranç açılış paketleri şimdi hazır",
    Site: "Site",
    Support: "Destek",
    "Log in": "Giriş yap",
    Theme: "Tema",
    "{n} free · {price}": "{n} ücretsiz · {price}",
    "{price} unlocks the whole pack": "{price} paketin tamamını açar",
    "Whole pack · {price}": "Paketin tamamı · {price}",
    "Whole pack · {price} — all {n} lines": "Paketin tamamı · {price} — {n} hattın tümü",
    "{n} free · {price} unlocks the whole pack": "{n} ücretsiz · {price} paketin tamamını açar",
    "Chess opening lessons": "Satranç açılış dersleri",
    "{n} lessons": "{n} ders",
    "Scotch Gambit Lessons": "Scotch Gambit dersleri",
    "Separate from drill packs. Buy all does not include lessons.":
      "Alıştırma paketlerinden ayrı. Hepsini satın al dersleri içermez.",
    "Lesson 1 is free": "Ders 1 ücretsiz",
    "Lessons 2 and 3 are {price}. A separate lesson purchase — not part of a drill pack, and not included in Buy all.":
      "2. ve 3. dersler {price}. Ayrı bir ders satın alımı — bir alıştırma paketi değil ve Hepsini satın al bunları içermez.",
    "Unlock the remaining lessons": "Kalan derslerin kilidini aç",
    "Back to lessons": "Derslere dön",
  },
};
