import type { Lang } from "./i18n";

/** Landing chrome. Prices stay in the catalog — never hard-code them here. */
export const LANDING_COPY: Record<Lang, Record<string, string>> = {
  en: {
    "Practice with hints. Test with none.": "Practice with hints. Test with none.",
    "Enter the gym": "Enter the gym",
    "Open now": "Open now",
    "Strict book-move trainer": "Strict book-move trainer",
    "Learning packs": "Learning packs",
    Support: "Support",
    "Log in": "Log in",
    Theme: "Theme",
    "{n} free · {price}": "{n} free · {price}",
  },
  es: {
    "Practice with hints. Test with none.": "Practica con pistas. El test, sin ninguna.",
    "Enter the gym": "Entra al gimnasio",
    "Open now": "Abierto ahora",
    "Strict book-move trainer": "Entrenador estricto de jugadas de libro",
    "Learning packs": "Paquetes de aprendizaje",
    Support: "Soporte",
    "Log in": "Entrar",
    Theme: "Tema",
    "{n} free · {price}": "{n} gratis · {price}",
  },
  zh: {
    "Practice with hints. Test with none.": "练习有提示。测验没有。",
    "Enter the gym": "进入训练馆",
    "Open now": "现已开放",
    "Strict book-move trainer": "严格的书谱走法训练",
    "Learning packs": "学习包",
    Support: "支持",
    "Log in": "登录",
    Theme: "主题",
    "{n} free · {price}": "{n} 免费 · {price}",
  },
  fr: {
    "Practice with hints. Test with none.": "Entraîne-toi avec des indices. Le test, sans aucun.",
    "Enter the gym": "Entre dans la salle",
    "Open now": "Ouvert maintenant",
    "Strict book-move trainer": "Entraîneur strict aux coups du livre",
    "Learning packs": "Packs d'apprentissage",
    Support: "Assistance",
    "Log in": "Connexion",
    Theme: "Thème",
    "{n} free · {price}": "{n} gratuit · {price}",
  },
  de: {
    "Practice with hints. Test with none.": "Üben mit Hinweisen. Testen ohne.",
    "Enter the gym": "In die Halle",
    "Open now": "Jetzt offen",
    "Strict book-move trainer": "Strenger Buchzug-Trainer",
    "Learning packs": "Lernpakete",
    Support: "Hilfe",
    "Log in": "Anmelden",
    Theme: "Design",
    "{n} free · {price}": "{n} gratis · {price}",
  },
  pt: {
    "Practice with hints. Test with none.": "Pratica com dicas. O teste, sem nenhuma.",
    "Enter the gym": "Entra no ginásio",
    "Open now": "Aberto agora",
    "Strict book-move trainer": "Treinador estrito de lances de livro",
    "Learning packs": "Pacotes de aprendizagem",
    Support: "Suporte",
    "Log in": "Entrar",
    Theme: "Tema",
    "{n} free · {price}": "{n} grátis · {price}",
  },
  ru: {
    "Practice with hints. Test with none.": "Тренировка с подсказками. Тест без них.",
    "Enter the gym": "Войти в зал",
    "Open now": "Уже открыто",
    "Strict book-move trainer": "Строгий тренажёр книжных ходов",
    "Learning packs": "Учебные пакеты",
    Support: "Поддержка",
    "Log in": "Войти",
    Theme: "Тема",
    "{n} free · {price}": "{n} бесплатно · {price}",
  },
  it: {
    "Practice with hints. Test with none.": "Allenati con i suggerimenti. Il test, senza.",
    "Enter the gym": "Entra in palestra",
    "Open now": "Aperto ora",
    "Strict book-move trainer": "Allenatore rigoroso delle mosse di libro",
    "Learning packs": "Pacchetti di studio",
    Support: "Supporto",
    "Log in": "Accedi",
    Theme: "Tema",
    "{n} free · {price}": "{n} gratis · {price}",
  },
  hi: {
    "Practice with hints. Test with none.": "अभ्यास संकेतों के साथ। परीक्षा बिना।",
    "Enter the gym": "जिम में प्रवेश",
    "Open now": "अभी खुला",
    "Strict book-move trainer": "सख्त बुक-मूव ट्रेनर",
    "Learning packs": "सीखने के पैक",
    Support: "सहायता",
    "Log in": "लॉग इन",
    Theme: "थीम",
    "{n} free · {price}": "{n} मुफ़्त · {price}",
  },
  ja: {
    "Practice with hints. Test with none.": "ヒントありで練習。テストはヒントなし。",
    "Enter the gym": "ジムに入る",
    "Open now": "公開中",
    "Strict book-move trainer": "厳密な定跡トレーナー",
    "Learning packs": "学習パック",
    Support: "サポート",
    "Log in": "ログイン",
    Theme: "テーマ",
    "{n} free · {price}": "{n} 無料 · {price}",
  },
  ar: {
    "Practice with hints. Test with none.": "تدرّب مع تلميحات. الاختبار بلا تلميح.",
    "Enter the gym": "ادخل الصالة",
    "Open now": "مفتوح الآن",
    "Strict book-move trainer": "مدرّب صارم لنقلات الكتاب",
    "Learning packs": "حزم التعلّم",
    Support: "الدعم",
    "Log in": "تسجيل الدخول",
    Theme: "المظهر",
    "{n} free · {price}": "{n} مجانًا · {price}",
  },
  tr: {
    "Practice with hints. Test with none.": "İpuçlarıyla çalış. Testte hiçbiri yok.",
    "Enter the gym": "Salona gir",
    "Open now": "Şimdi açık",
    "Strict book-move trainer": "Katı kitap-hamlesi antrenörü",
    "Learning packs": "Öğrenme paketleri",
    Support: "Destek",
    "Log in": "Giriş yap",
    Theme: "Tema",
    "{n} free · {price}": "{n} ücretsiz · {price}",
  },
};
