/**
 * Compact public-domain / CC0 ECO distill for Create-your-own authoring.
 * SAN from the start position. Deepest/longest entry wins on a shared FEN.
 * Not a catalog pack list — curated packs stay in packs.ts.
 */
export type OpeningBookRow = {
  eco: string;
  name: string;
  /** Space-separated SAN from the start position. */
  moves: string;
};

export const OPENING_IDENTITY_BOOK: readonly OpeningBookRow[] = [
  { eco: "B00", name: "King's Pawn Opening", moves: "e4" },
  { eco: "C20", name: "Open Game", moves: "e4 e5" },
  { eco: "C40", name: "King's Knight Opening", moves: "e4 e5 Nf3" },
  { eco: "C44", name: "King's Knight Opening", moves: "e4 e5 Nf3 Nc6" },
  { eco: "C50", name: "Italian Game", moves: "e4 e5 Nf3 Nc6 Bc4" },
  { eco: "C50", name: "Giuoco Piano", moves: "e4 e5 Nf3 Nc6 Bc4 Bc5" },
  { eco: "C50", name: "Giuoco Pianissimo", moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 d3" },
  { eco: "C53", name: "Giuoco Piano", moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 c3" },
  { eco: "C54", name: "Giuoco Piano", moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6" },
  { eco: "C51", name: "Evans Gambit", moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 b4" },
  { eco: "C52", name: "Evans Gambit", moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5" },
  { eco: "C50", name: "Hungarian Defence", moves: "e4 e5 Nf3 Nc6 Bc4 Be7" },
  { eco: "C55", name: "Two Knights Defence", moves: "e4 e5 Nf3 Nc6 Bc4 Nf6" },
  { eco: "C55", name: "Two Knights Defence", moves: "e4 e5 Nf3 Nc6 Bc4 Nf6 d3" },
  { eco: "C57", name: "Two Knights Defence", moves: "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5" },
  { eco: "C58", name: "Two Knights Defence", moves: "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5" },
  { eco: "C60", name: "Ruy Lopez", moves: "e4 e5 Nf3 Nc6 Bb5" },
  { eco: "C70", name: "Ruy Lopez", moves: "e4 e5 Nf3 Nc6 Bb5 a6" },
  { eco: "C68", name: "Ruy Lopez, Exchange", moves: "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6" },
  { eco: "C77", name: "Ruy Lopez", moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6" },
  { eco: "C84", name: "Ruy Lopez, Closed", moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7" },
  { eco: "C80", name: "Ruy Lopez, Open", moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Nxe4" },
  { eco: "C65", name: "Berlin Defence", moves: "e4 e5 Nf3 Nc6 Bb5 Nf6" },
  { eco: "C67", name: "Berlin Defence", moves: "e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4" },
  { eco: "C64", name: "Ruy Lopez, Classical", moves: "e4 e5 Nf3 Nc6 Bb5 Bc5" },
  { eco: "C63", name: "Schliemann Defence", moves: "e4 e5 Nf3 Nc6 Bb5 f5" },
  { eco: "C62", name: "Ruy Lopez, Steinitz", moves: "e4 e5 Nf3 Nc6 Bb5 d6" },
  { eco: "C44", name: "Scotch Game", moves: "e4 e5 Nf3 Nc6 d4" },
  { eco: "C45", name: "Scotch Game", moves: "e4 e5 Nf3 Nc6 d4 exd4 Nxd4" },
  { eco: "C44", name: "Scotch Gambit", moves: "e4 e5 Nf3 Nc6 d4 exd4 Bc4" },
  { eco: "C46", name: "Three Knights Game", moves: "e4 e5 Nf3 Nc6 Nc3" },
  { eco: "C47", name: "Four Knights Game", moves: "e4 e5 Nf3 Nc6 Nc3 Nf6" },
  { eco: "C48", name: "Four Knights Game", moves: "e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5" },
  { eco: "C47", name: "Four Knights Game", moves: "e4 e5 Nf3 Nc6 Nc3 Nf6 d4" },
  { eco: "C44", name: "Ponziani Opening", moves: "e4 e5 Nf3 Nc6 c3" },
  { eco: "C30", name: "King's Gambit", moves: "e4 e5 f4" },
  { eco: "C33", name: "King's Gambit Accepted", moves: "e4 e5 f4 exf4" },
  { eco: "C31", name: "Falkbeer Countergambit", moves: "e4 e5 f4 d5" },
  { eco: "C25", name: "Vienna Game", moves: "e4 e5 Nc3" },
  { eco: "C26", name: "Vienna Game", moves: "e4 e5 Nc3 Nf6" },
  { eco: "C23", name: "Bishop's Opening", moves: "e4 e5 Bc4" },
  { eco: "C21", name: "Centre Game", moves: "e4 e5 d4" },
  { eco: "C42", name: "Petroff Defence", moves: "e4 e5 Nf3 Nf6" },
  { eco: "C42", name: "Petroff Defence", moves: "e4 e5 Nf3 Nf6 Nxe5 d6" },
  { eco: "C42", name: "Stafford Gambit", moves: "e4 e5 Nf3 Nf6 Nxe5 Nc6" },
  { eco: "C41", name: "Philidor Defence", moves: "e4 e5 Nf3 d6" },
  { eco: "C40", name: "Latvian Gambit", moves: "e4 e5 Nf3 f5" },
  { eco: "C40", name: "Elephant Gambit", moves: "e4 e5 Nf3 d5" },

  { eco: "B20", name: "Sicilian Defence", moves: "e4 c5" },
  { eco: "B27", name: "Sicilian Defence", moves: "e4 c5 Nf3" },
  { eco: "B50", name: "Sicilian Defence", moves: "e4 c5 Nf3 d6" },
  { eco: "B54", name: "Open Sicilian", moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3" },
  { eco: "B90", name: "Sicilian Najdorf", moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6" },
  { eco: "B70", name: "Sicilian Dragon", moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6" },
  { eco: "B80", name: "Sicilian Scheveningen", moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6" },
  { eco: "B56", name: "Classical Sicilian", moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6" },
  { eco: "B51", name: "Moscow Variation", moves: "e4 c5 Nf3 d6 Bb5+" },
  { eco: "B30", name: "Sicilian Defence", moves: "e4 c5 Nf3 Nc6" },
  { eco: "B32", name: "Open Sicilian", moves: "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4" },
  { eco: "B33", name: "Sveshnikov Sicilian", moves: "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5" },
  { eco: "B34", name: "Accelerated Dragon", moves: "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6" },
  { eco: "B30", name: "Rossolimo Variation", moves: "e4 c5 Nf3 Nc6 Bb5" },
  { eco: "B40", name: "Sicilian Defence", moves: "e4 c5 Nf3 e6" },
  { eco: "B41", name: "Sicilian Kan", moves: "e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6" },
  { eco: "B44", name: "Sicilian Taimanov", moves: "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6" },
  { eco: "B29", name: "Nimzowitsch Sicilian", moves: "e4 c5 Nf3 Nf6" },
  { eco: "B22", name: "Alapin Sicilian", moves: "e4 c5 c3" },
  { eco: "B23", name: "Closed Sicilian", moves: "e4 c5 Nc3" },
  { eco: "B24", name: "Closed Sicilian", moves: "e4 c5 Nc3 Nc6 g3" },
  { eco: "B21", name: "Smith-Morra Gambit", moves: "e4 c5 d4 cxd4 c3" },
  { eco: "B21", name: "Grand Prix Attack", moves: "e4 c5 f4" },
  { eco: "B20", name: "Wing Gambit", moves: "e4 c5 b4" },

  { eco: "C00", name: "French Defence", moves: "e4 e6" },
  { eco: "C00", name: "French Defence", moves: "e4 e6 d4 d5" },
  { eco: "C10", name: "French Defence", moves: "e4 e6 d4 d5 Nc3" },
  { eco: "C15", name: "French Winawer", moves: "e4 e6 d4 d5 Nc3 Bb4" },
  { eco: "C11", name: "French Classical", moves: "e4 e6 d4 d5 Nc3 Nf6" },
  { eco: "C10", name: "French Rubinstein", moves: "e4 e6 d4 d5 Nc3 dxe4" },
  { eco: "C03", name: "French Tarrasch", moves: "e4 e6 d4 d5 Nd2" },
  { eco: "C02", name: "French Advance", moves: "e4 e6 d4 d5 e5" },
  { eco: "C01", name: "French Exchange", moves: "e4 e6 d4 d5 exd5" },

  { eco: "B10", name: "Caro-Kann Defence", moves: "e4 c6" },
  { eco: "B12", name: "Caro-Kann Defence", moves: "e4 c6 d4 d5" },
  { eco: "B15", name: "Caro-Kann Defence", moves: "e4 c6 d4 d5 Nc3" },
  { eco: "B18", name: "Caro-Kann Classical", moves: "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5" },
  { eco: "B15", name: "Caro-Kann Defence", moves: "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6" },
  { eco: "B12", name: "Caro-Kann Advance", moves: "e4 c6 d4 d5 e5" },
  { eco: "B13", name: "Caro-Kann Exchange", moves: "e4 c6 d4 d5 exd5 cxd5" },
  { eco: "B13", name: "Panov-Botvinnik Attack", moves: "e4 c6 d4 d5 exd5 cxd5 c4" },
  { eco: "B11", name: "Caro-Kann Two Knights", moves: "e4 c6 Nc3 d5 Nf3" },
  { eco: "B12", name: "Caro-Kann Fantasy", moves: "e4 c6 d4 d5 f3" },

  { eco: "B01", name: "Scandinavian Defence", moves: "e4 d5" },
  { eco: "B01", name: "Scandinavian Defence", moves: "e4 d5 exd5 Qxd5 Nc3 Qa5" },
  { eco: "B01", name: "Scandinavian Defence", moves: "e4 d5 exd5 Nf6" },
  { eco: "B07", name: "Pirc Defence", moves: "e4 d6" },
  { eco: "B07", name: "Pirc Defence", moves: "e4 d6 d4 Nf6 Nc3 g6" },
  { eco: "B07", name: "Pirc 150 Attack", moves: "e4 d6 d4 Nf6 Nc3 g6 Be3" },
  { eco: "B06", name: "Modern Defence", moves: "e4 g6" },
  { eco: "B02", name: "Alekhine's Defence", moves: "e4 Nf6" },
  { eco: "B04", name: "Alekhine's Defence", moves: "e4 Nf6 e5 Nd5 d4 d6 Nf3" },
  { eco: "B00", name: "Nimzowitsch Defence", moves: "e4 Nc6" },
  { eco: "B00", name: "Owen's Defence", moves: "e4 b6" },

  { eco: "A40", name: "Queen's Pawn Opening", moves: "d4" },
  { eco: "D00", name: "Queen's Pawn Game", moves: "d4 d5" },
  { eco: "D06", name: "Queen's Gambit", moves: "d4 d5 c4" },
  { eco: "D30", name: "Queen's Gambit Declined", moves: "d4 d5 c4 e6" },
  { eco: "D35", name: "Queen's Gambit Declined", moves: "d4 d5 c4 e6 Nc3 Nf6" },
  { eco: "D50", name: "Queen's Gambit Declined", moves: "d4 d5 c4 e6 Nc3 Nf6 Bg5" },
  { eco: "D35", name: "QGD Exchange", moves: "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5" },
  { eco: "E01", name: "Catalan Opening", moves: "d4 d5 c4 e6 Nf3 Nf6 g3" },
  { eco: "D10", name: "Slav Defence", moves: "d4 d5 c4 c6" },
  { eco: "D15", name: "Slav Defence", moves: "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4" },
  { eco: "D43", name: "Semi-Slav Defence", moves: "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6" },
  { eco: "D20", name: "Queen's Gambit Accepted", moves: "d4 d5 c4 dxc4" },
  { eco: "D02", name: "London System", moves: "d4 d5 Nf3 Nf6 Bf4" },
  { eco: "D00", name: "London System", moves: "d4 d5 Bf4" },
  { eco: "D01", name: "Richter-Veresov Attack", moves: "d4 d5 Nc3 Nf6 Bg5" },
  { eco: "D00", name: "Blackmar-Diemer Gambit", moves: "d4 d5 e4" },
  { eco: "A45", name: "Indian Defence", moves: "d4 Nf6" },
  { eco: "E00", name: "Indian Defence", moves: "d4 Nf6 c4 e6" },
  { eco: "E20", name: "Nimzo-Indian Defence", moves: "d4 Nf6 c4 e6 Nc3 Bb4" },
  { eco: "E12", name: "Queen's Indian Defence", moves: "d4 Nf6 c4 e6 Nf3 b6" },
  { eco: "E00", name: "Catalan Opening", moves: "d4 Nf6 c4 e6 g3" },
  { eco: "D37", name: "Queen's Gambit Declined", moves: "d4 Nf6 c4 e6 Nf3 d5" },
  { eco: "E61", name: "King's Indian Defence", moves: "d4 Nf6 c4 g6 Nc3 Bg7" },
  { eco: "D80", name: "Grünfeld Defence", moves: "d4 Nf6 c4 g6 Nc3 d5" },
  { eco: "E60", name: "King's Indian Defence", moves: "d4 Nf6 c4 g6 Nf3 Bg7 g3" },
  { eco: "A56", name: "Benoni Defence", moves: "d4 Nf6 c4 c5" },
  { eco: "A60", name: "Modern Benoni", moves: "d4 Nf6 c4 c5 d5 e6" },
  { eco: "A51", name: "Budapest Gambit", moves: "d4 Nf6 c4 e5" },
  { eco: "A45", name: "London System", moves: "d4 Nf6 Bf4" },
  { eco: "D00", name: "Jobava London", moves: "d4 Nf6 Nc3 d5 Bf4" },
  { eco: "A80", name: "Dutch Defence", moves: "d4 f5" },
  { eco: "A81", name: "Dutch Defence", moves: "d4 f5 g3 Nf6 Bg2" },
  { eco: "A40", name: "Englund Gambit", moves: "d4 e5" },
  { eco: "A43", name: "Old Benoni", moves: "d4 c5" },

  { eco: "A10", name: "English Opening", moves: "c4" },
  { eco: "A20", name: "English Opening", moves: "c4 e5" },
  { eco: "A30", name: "English Opening, Symmetrical", moves: "c4 c5" },
  { eco: "A15", name: "English Opening", moves: "c4 Nf6" },
  { eco: "A13", name: "English Opening", moves: "c4 e6" },
  { eco: "A11", name: "English Opening", moves: "c4 c6" },

  { eco: "A04", name: "Réti Opening", moves: "Nf3" },
  { eco: "A06", name: "Réti Opening", moves: "Nf3 d5" },
  { eco: "A09", name: "Réti Opening", moves: "Nf3 d5 c4" },
  { eco: "A05", name: "King's Indian Attack", moves: "Nf3 Nf6 g3" },
  { eco: "A01", name: "Nimzo-Larsen Attack", moves: "b3" },
  { eco: "A02", name: "Bird's Opening", moves: "f4" },
  { eco: "A00", name: "Benko Opening", moves: "g3" },
  { eco: "A00", name: "Sokolsky Opening", moves: "b4" },
];
