/** UI strings for the website mate puzzle. Merged into every language dict. */
export const PUZZLE_COPY: Record<string, Record<string, string>> = {
  en: {
    Puzzle: "Puzzle",
    "Today's puzzle": "Today's puzzle",
    "White to move · Mate in 2": "White to move · Mate in 2",
    "Mate in 2": "Mate in 2",
    Hint: "Hint",
    Retry: "Retry",
    "That's mate.": "That's mate.",
  },
  es: {
    Puzzle: "Puzzle",
    "Today's puzzle": "El puzzle de hoy",
    "White to move · Mate in 2": "Blancas juegan · Mate en 2",
    "Mate in 2": "Mate en 2",
    Hint: "Pista",
    Retry: "Reintentar",
    "That's mate.": "Eso es mate.",
  },
  zh: {
    Puzzle: "谜题",
    "Today's puzzle": "今日谜题",
    "White to move · Mate in 2": "白方行棋 · 两步将杀",
    "Mate in 2": "两步将杀",
    Hint: "提示",
    Retry: "再试",
    "That's mate.": "将杀。",
  },
  fr: {
    Puzzle: "Puzzle",
    "Today's puzzle": "Le puzzle du jour",
    "White to move · Mate in 2": "Trait aux Blancs · Mat en 2",
    "Mate in 2": "Mat en 2",
    Hint: "Indice",
    Retry: "Réessayer",
    "That's mate.": "C'est mat.",
  },
  de: {
    Puzzle: "Rätsel",
    "Today's puzzle": "Rätsel des Tages",
    "White to move · Mate in 2": "Weiß am Zug · Matt in 2",
    "Mate in 2": "Matt in 2",
    Hint: "Hinweis",
    Retry: "Nochmal",
    "That's mate.": "Das ist Matt.",
  },
  pt: {
    Puzzle: "Puzzle",
    "Today's puzzle": "O puzzle de hoje",
    "White to move · Mate in 2": "Brancas jogam · Mate em 2",
    "Mate in 2": "Mate em 2",
    Hint: "Dica",
    Retry: "Tentar de novo",
    "That's mate.": "É mate.",
  },
  ru: {
    Puzzle: "Задача",
    "Today's puzzle": "Задача дня",
    "White to move · Mate in 2": "Ход белых · Мат в 2",
    "Mate in 2": "Мат в 2",
    Hint: "Подсказка",
    Retry: "Ещё раз",
    "That's mate.": "Это мат.",
  },
  it: {
    Puzzle: "Puzzle",
    "Today's puzzle": "Il puzzle di oggi",
    "White to move · Mate in 2": "Tocca al Bianco · Matto in 2",
    "Mate in 2": "Matto in 2",
    Hint: "Suggerimento",
    Retry: "Riprova",
    "That's mate.": "È matto.",
  },
  hi: {
    Puzzle: "पज़ल",
    "Today's puzzle": "आज का पज़ल",
    "White to move · Mate in 2": "सफेद की चाल · 2 में मैट",
    "Mate in 2": "2 में मैट",
    Hint: "संकेत",
    Retry: "फिर कोशिश करें",
    "That's mate.": "यह मैट है।",
  },
  ja: {
    Puzzle: "パズル",
    "Today's puzzle": "今日のパズル",
    "White to move · Mate in 2": "白番 · 2手メイト",
    "Mate in 2": "2手メイト",
    Hint: "ヒント",
    Retry: "やり直す",
    "That's mate.": "メイトです。",
  },
  ar: {
    Puzzle: "لغز",
    "Today's puzzle": "لغز اليوم",
    "White to move · Mate in 2": "دور الأبيض · مات في 2",
    "Mate in 2": "مات في 2",
    Hint: "تلميح",
    Retry: "حاول مجددًا",
    "That's mate.": "هذا مات.",
  },
  tr: {
    Puzzle: "Bulmaca",
    "Today's puzzle": "Günün bulmacası",
    "White to move · Mate in 2": "Beyaz oynar · 2 hamlede mat",
    "Mate in 2": "2 hamlede mat",
    Hint: "İpucu",
    Retry: "Yeniden dene",
    "That's mate.": "Bu mat.",
  },
};
