/**
 * Two-card intro copy for every drill pack except Slav and QGD,
 * which keep their own cards in pack-study-intro.ts.
 * Stems are the defining moves the board plays by itself.
 */

export type StudyPackRow = {
  packId: string;
  firstLineId: string;
  name: string;
  side: "w" | "b" | "mixed";
  lineCount: number;
  line1Free: boolean;
  stem: readonly string[];
  tagline: string;
  lead: string;
  rest: string;
};

export const STUDY_PACK_ROWS: readonly StudyPackRow[] = [
  {
    packId: "caro-kann-black",
    firstLineId: "ckb1",
    name: "Caro-Kann for Black",
    side: "b",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "c6", "d4", "d5"],
    tagline: "A solid centre. An easy bishop. A clear reply.",
    lead: "The Caro-Kann is 1.e4 c6 2.d4 d5. Black takes a pawn centre and gets the light-squared bishop out before playing ...e6.",
    rest: "It is named after Horatio Caro and Marcus Kann, who published it in 1886. It is worth learning because the same two moves meet the main ways White continues, and the structure stays sound. The 10 lines in this pack are the Advance, the Classical, the Exchange, the Panov, the Two Knights, and the Fantasy, including replies when White plays a loose move.",
  },
  {
    packId: "london-black",
    firstLineId: "alb1",
    name: "Fight the London",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "d5", "Bf4"],
    tagline: "Meet the bishop on f4 with a plan.",
    lead: "The London System is White's 1.d4 with an early Bf4. The dark-squared bishop comes out before the centre is closed, and the same shell meets a lot of Black setups.",
    rest: "The name comes from the London tournament of 1922, where this bishop development was used again and again. It is worth learning a reply because you will see it in club games. The lines cover a Caro-style ...c6, Classical ...c5, Dubov ...Nh5, a Carlsen ...Bd6 idea, symmetry, a Grünfeld shell, the Chigorin, the Jobava, and an early ...c5.",
  },
  {
    packId: "d4-sidelines-black",
    firstLineId: "d4s1",
    name: "1.d4 Sideline Survival Kit",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "d5"],
    tagline: "A book reply for each sideline.",
    lead: "After 1.d4, not every White player chooses a main queen's pawn opening. This pack is Black's book against the Colle, the Torre, the Trompowsky, the Veresov, and the Blackmar-Diemer.",
    rest: "These are club weapons with their own history. The Colle and Torre keep a quiet centre. The Trompowsky and Veresov pin or trade the knight on f6. The Blackmar-Diemer offers a pawn for a quick attack. The lines cover a central challenge, quiet development, and a separate reply for each of those tries.",
  },
  {
    packId: "anti-sicilian-black",
    firstLineId: "as1",
    name: "Anti-Sicilian Survival Kit",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "c5"],
    tagline: "Still a Sicilian. A different White plan.",
    lead: "An anti-Sicilian is White answering 1.e4 c5 without the open 2.Nf3 and 3.d4 centre. This pack meets the Alapin, the Grand Prix, the Closed Sicilian, the Smith-Morra, the Rossolimo, the Wing Gambit, and 2.f4.",
    rest: "These sidelines are as old as the Open Sicilian and very common in club play. It is worth knowing them so a surprise second move does not throw you off 1...c5. The lines take a share of the centre, develop, and finish the shell for each White choice.",
  },
  {
    packId: "nimzo-larsen-white",
    firstLineId: "nl1",
    name: "Nimzo-Larsen Attack for White",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["b3"],
    tagline: "A flank bishop. Pressure on the centre.",
    lead: "The Nimzo-Larsen Attack is 1.b3. White fianchettoes the queen's bishop and pressures the centre from the flank.",
    rest: "It is named after Aron Nimzowitsch and Bent Larsen, who both showed that 1.b3 can be a real system. It is worth learning because one setup meets many Black replies. The lines cover ...e5, ...d5, ...c5, ...Nf6, a kingside fianchetto, ...f5, ...d6, and the later c4 break.",
  },
  {
    packId: "italian-white",
    firstLineId: "it1",
    name: "Italian Game for White",
    side: "w",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nc6", "Bc4"],
    tagline: "A classical centre. A bishop aimed at f7.",
    lead: "The Italian Game is 1.e4 e5 2.Nf3 Nc6 3.Bc4. White develops fast and looks toward the pawn on f7.",
    rest: "It is one of the oldest open games, taught in the Italian schools of the 16th and 17th centuries. It is worth learning because the same three moves meet several Black defences. The 10 lines cover the quiet Giuoco Pianissimo, the Two Knights, the Hungarian, ...d6, the kingside fianchetto, the Fried Liver, the classical centre, and replies to a loose Black move.",
  },
  {
    packId: "french-white",
    firstLineId: "fr1",
    name: "French Defence for White: Advance & Tarrasch",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "e6", "d4", "d5"],
    tagline: "Choose the centre. Then play that plan.",
    lead: "The French Defence is 1.e4 e6 2.d4 d5. Black challenges the e-pawn at once and accepts a cramped light-squared bishop for a solid centre.",
    rest: "The name comes from a London versus Paris correspondence game in 1834. As White you choose the fight. The lines cover the Advance, the Tarrasch, the Classical, the Winawer, and the Exchange, including development once the centre is set.",
  },
  {
    packId: "alapin-white",
    firstLineId: "al1",
    name: "How to Meet the Sicilian: The Alapin for White",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "c5", "c3"],
    tagline: "A pawn centre against the Sicilian.",
    lead: "The Alapin is 1.e4 c5 2.c3. White prepares d4 and a classical pawn centre instead of the Open Sicilian's piece play.",
    rest: "It is named after Semyon Alapin, who used 2.c3 to sidestep the sharp open variations. It is worth learning if you want a calm answer to 1...c5. The lines meet ...Nc6, ...d5, ...Nf6, ...e6, ...d6, and ...g6, then finish development around the d4 pawn.",
  },
  {
    packId: "english-black",
    firstLineId: "en1",
    name: "How to Meet 1.c4: The Symmetrical English for Black",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["c4", "c5"],
    tagline: "Mirror the c-pawn. Choose the break.",
    lead: "The Symmetrical English is 1.c4 c5. Black mirrors the c-pawn and waits for the right central break.",
    rest: "The English Opening, 1.c4, was a favourite of Howard Staunton in the 19th century. The symmetrical reply is worth learning because it stays flexible. The lines cover the double fianchetto, the Four Knights, an early d4, the Botvinnik, the closed system, e3, the Hedgehog, and queenside expansion.",
  },
  {
    packId: "kg-black",
    firstLineId: "kg1",
    name: "How to Defend Against the King’s Gambit",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "e5", "f4"],
    tagline: "Take the pawn, or take the centre.",
    lead: "The King's Gambit is 1.e4 e5 2.f4. White offers a pawn to open the f-file and claim the centre.",
    rest: "It is one of the great romantic openings, played for centuries before quieter systems took over. It is worth a book reply because a surprised Black can lose quickly. The lines cover the Knight's Gambit, the Bishop's Gambit, the Falkbeer, a declined centre, and the Fischer Defence, including the Falkbeer trap the pack already names.",
  },
  {
    packId: "scandinavian-white",
    firstLineId: "sc1",
    name: "How to Meet the Scandinavian Defence: White’s Safe Edge",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "d5"],
    tagline: "A tempo on the queen. A normal centre.",
    lead: "The Scandinavian is 1.e4 d5. Black hits the e-pawn at once, and after 2.exd5 the queen or a knight recaptures.",
    rest: "It is one of the oldest answers to 1.e4, also called the Centre Counter. White's edge is the tempo on a queen that comes out early. The lines cover the classical queen on a5, the Qd6 and Qd8 routes, the modern ...Nf6 recapture, and the sharper Portuguese and Icelandic lines.",
  },
  {
    packId: "pirc-150-white",
    firstLineId: "pm1",
    name: "How to Meet the Pirc & Modern Defence: The 150 Attack",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "d6", "d4", "Nf6", "Nc3", "g6"],
    tagline: "A pawn centre. A simple attacking shell.",
    lead: "The Pirc is 1.e4 d6 2.d4 Nf6 3.Nc3 g6. The Modern is the same fianchetto idea without an early ...Nf6. Black lets White take the centre, then chips at it.",
    rest: "The Pirc is named after Vasja Pirc. The 150 Attack is White's Be3 and Qd2 shell against that bishop on g7. It is a practical club system because the same moves meet both defences. The lines cover ...c6, ...a6, ...Ng4, ...e5, and the Modern's queenside expansion.",
  },
  {
    packId: "dutch-fianchetto-white",
    firstLineId: "du1",
    name: "How to Meet the Dutch Defence: The Fianchetto System for White",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "f5"],
    tagline: "A calm fianchetto against ...f5.",
    lead: "The Dutch Defence is 1.d4 f5. Black fights for e4 and accepts some looseness around the king.",
    rest: "Elias Stein recommended 1...f5 for Dutch players in 1789, and the defence has stayed a fighting answer to 1.d4. A kingside fianchetto is a calm way to meet it. The lines cover the Classical Dutch, the Stonewall, the Leningrad, and the flexible move orders, including the ...e5 break.",
  },
  {
    packId: "caro-advance-panov-white",
    firstLineId: "ckw1",
    name: "How to Meet the Caro-Kann: Advance & Panov for White",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "c6", "d4", "d5"],
    tagline: "Space with e5, or an open centre.",
    lead: "The Caro-Kann is 1.e4 c6 2.d4 d5. Black wants a solid centre and an easy light-squared bishop. This pack is White's Advance and Panov answers.",
    rest: "The Advance, 3.e5, takes space. The Panov, 3.exd5 cxd5 4.c4, opens the centre. Both ask the Caro a direct question, which is why they are worth a repertoire. The lines cover ...Bf5, ...c5, the bishop retreat, and the Panov development against the isolated queen pawn.",
  },
  {
    packId: "evans-black",
    firstLineId: "evb1",
    name: "How to Defend Against the Evans Gambit for Black",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4"],
    tagline: "A pawn offer. A calm retreat.",
    lead: "The Evans Gambit is an Italian with 4.b4. White offers a pawn so the bishop on c5 leaves the a7 to g1 diagonal, then strikes with c3 and d4.",
    rest: "Captain Evans introduced 4.b4 in the 1820s, and it became a favourite attacking line of the 19th century. It is worth a book reply because the attack on f7 is real. The lines accept and retreat with ...Ba5 or ...Be7, decline with ...Bb6, and finish development without grabbing every pawn.",
  },
  {
    packId: "englund-white",
    firstLineId: "eg1",
    name: "How to Meet the Englund Gambit: White’s Safe Route",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "e5"],
    tagline: "Take on e5. Develop. Stay calm.",
    lead: "The Englund Gambit is 1.d4 e5. Black offers a pawn on move one to pull White's pieces into a raid.",
    rest: "It is named after Fritz Englund. Accepted with 2.dxe5, Black often tries ...Nc6 and ...Qe7. It is worth a safe route because the queen raid is the whole idea. The lines take on e5, meet ...Qe7, ...d6, and ...f6, and develop without handing the extra pawn back for nothing.",
  },
  {
    packId: "budapest-white",
    firstLineId: "bp1",
    name: "How to Meet the Budapest Gambit: White’s Safe Route",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "Nf6", "c4", "e5"],
    tagline: "A pawn in hand. Development first.",
    lead: "The Budapest Gambit is 1.d4 Nf6 2.c4 e5. Black offers a pawn to open lines and jump a knight to g4 or e4.",
    rest: "It was worked out in Budapest in 1916. The usual recapture is 3.dxe5 Ng4, and the Fajarowicz is 3...Ne4. It is worth a safe route so the extra pawn is not lost to a cheap idea. The lines cover 4.Bf4, 4.e3, 4.Nf3, the Qd5 main line, a decline with 3.e3, and the queen trap warning the pack already includes.",
  },
  {
    packId: "bdg-black",
    firstLineId: "bdg1",
    name: "How to Defend Against the Blackmar–Diemer Gambit for Black",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "d5", "e4"],
    tagline: "Take the pawn. Finish development.",
    lead: "The Blackmar-Diemer Gambit is 1.d4 d5 2.e4 dxe4 3.Nc3 Nf6 4.f3. White offers a pawn to open the f-file and attack.",
    rest: "Armand Blackmar tried the idea in the 19th century, and Emil Josef Diemer made it a club favourite in the 20th. It is worth a book reply because the plans look simple and the attack can be fast. The lines cover the Gunderam ...Bf5, the Teichmann ...Bg4, the Euwe ...e6, and the Bogoljubow ...g6.",
  },
  {
    packId: "qg-white",
    firstLineId: "qg1",
    name: "Queen’s Gambit for White",
    side: "w",
    lineCount: 10,
    line1Free: true,
    stem: ["d4", "d5", "c4"],
    tagline: "A wing pawn. A fight for the centre.",
    lead: "The Queen's Gambit is 1.d4 d5 2.c4. White offers a wing pawn to challenge Black's centre.",
    rest: "It is one of the oldest queen's pawn openings and a world championship staple. It is worth learning because one move, c4, meets several Black defences. The 10 lines cover the Queen's Gambit Declined, the Accepted, the Slav, the Semi-Slav, the Chigorin, and the Albin, including replies to a loose central break.",
  },
  {
    packId: "opening-traps",
    firstLineId: "ot1",
    name: "Opening Traps",
    side: "mixed",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "d6", "Bc4"],
    tagline: "Short patterns. The book move matters.",
    lead: "This pack is ten short traps, not one opening. Each line is a known pattern where the greedy take loses.",
    rest: "Legal's Mate, the first line, is named after the 18th century player Sire de Légal. The other lines are just as concrete. They are the Fishing Pole, the Elephant, the Lasker Albin, the Blackburne Shilling, the Stafford, the Englund, the queen's gambit accepted trap, the Damiano, and the Budapest Kieninger. The board behind this card plays the start of Legal's Mate.",
  },
  {
    packId: "scotch",
    firstLineId: "sg1",
    name: "Scotch Gambit (White)",
    side: "w",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Bc4"],
    tagline: "Open the centre. Develop the bishop.",
    lead: "The Scotch Gambit is 1.e4 e5 2.Nf3 Nc6 3.d4 exd4 4.Bc4. White opens the centre and develops the bishop instead of taking back on d4 at once.",
    rest: "The Scotch Game is named after an Edinburgh versus London correspondence match in 1824. The gambit with 4.Bc4 is the sharp branch. It is worth learning because the open d-file rewards exact move order. The 10 lines cover the Canal, the Greco, the Max Lange, the Ghulam-Kassim, and ...Be7, including replies when Black takes too much.",
  },
  {
    packId: "london",
    firstLineId: "lon1",
    name: "London System (White)",
    side: "w",
    lineCount: 10,
    line1Free: true,
    stem: ["d4", "d5", "Bf4"],
    tagline: "One setup. Many Black replies.",
    lead: "The London System is 1.d4 with an early Bf4. White builds a solid centre with e3 and often c3, and the dark-squared bishop is out.",
    rest: "The system took its name from the London tournament of 1922. It is worth learning because the same moves meet ...d5, ...c5, a king's Indian, and Indian move orders. The 10 lines cover those shells, the ...Qb6 idea, and ...Nc6, including replies to a loose ...e5 or ...Ne4.",
  },
  {
    packId: "english-white",
    firstLineId: "engw1",
    name: "English Opening for White",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["c4"],
    tagline: "Control d5 from the flank.",
    lead: "The English Opening is 1.c4. White controls d5 from the side and chooses the structure after Black's reply.",
    rest: "Howard Staunton used 1.c4 in his 1843 match with Saint-Amant, and the opening has been a main repertoire choice ever since. The lines cover the Four Knights, the Botvinnik, the symmetrical English, the Hedgehog, the Mikenas, and replies to a king's Indian, a Slav shell, and the Dutch.",
  },
  {
    packId: "catalan-white",
    firstLineId: "catw1",
    name: "Catalan Opening for White",
    side: "w",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "Nf6", "c4", "e6", "g3"],
    tagline: "A fianchetto. Pressure down the long diagonal.",
    lead: "The Catalan is 1.d4 Nf6 2.c4 e6 3.g3. White fianchettoes the king's bishop and combines a queen's pawn centre with pressure on the long diagonal.",
    rest: "The name comes from the 1929 Barcelona tournament. It is worth learning because Open and Closed Catalan plans are different, and mixing them is the usual mistake. The lines cover the Open Catalan, the Closed Catalan, and the Bogo-Catalan.",
  },
  {
    packId: "nimzo-indian-black",
    firstLineId: "nib1",
    name: "Nimzo-Indian Defence",
    side: "b",
    lineCount: 20,
    line1Free: true,
    stem: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4"],
    tagline: "Pin the knight. Fight the centre.",
    lead: "The Nimzo-Indian is 1.d4 Nf6 2.c4 e6 3.Nc3 Bb4. Black pins the knight on c3 and fights for control of e4.",
    rest: "It is named after Aron Nimzowitsch, who showed that the pin can be a full defence to 1.d4. It is a world championship staple because the same bishop move meets many White systems. The lines cover the Classical, the Rubinstein, the Sämisch, the Leningrad, and the quieter 4.Nf3 and 4.Qb3 tries.",
  },
  {
    packId: "grunfeld-black",
    firstLineId: "gfb1",
    name: "Grünfeld Defence",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "Nf6", "c4", "g6", "Nc3", "d5"],
    tagline: "Let White take the centre. Then strike.",
    lead: "The Grünfeld is 1.d4 Nf6 2.c4 g6 with ...d5. Black allows a big white centre, then attacks it with pieces and ...c5.",
    rest: "Ernst Grünfeld introduced the defence in 1922. It is worth learning because the counterattack is concrete: you need the book move, not a general idea. The lines cover the Exchange, the Russian System, the fianchetto, and the quieter Bg5 and Bf4 tries.",
  },
  {
    packId: "petroff-black",
    firstLineId: "peb1",
    name: "Petroff Defence",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nf6"],
    tagline: "Answer 2.Nf3 with 2...Nf6.",
    lead: "The Petroff Defence is 1.e4 e5 2.Nf3 Nf6. Black answers the attack on e5 by attacking e4.",
    rest: "It is named after the Russian player Alexander Petrov. It has a reputation as a solid equaliser, which is why it is worth a repertoire. The lines cover the classical ...d5, the Steinitz 3.d4, the Nimzowitsch 5.Nc3, and the quieter queen and bishop moves.",
  },
  {
    packId: "berlin-black",
    firstLineId: "berb1",
    name: "Berlin Defence",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6"],
    tagline: "A Spanish reply. An endgame you can trust.",
    lead: "The Berlin Defence is 1.e4 e5 2.Nf3 Nc6 3.Bb5 Nf6. Black answers the Ruy Lopez by attacking the e4 pawn.",
    rest: "The main line leads to the Berlin endgame, which became a world championship choice when Vladimir Kramnik used it against Garry Kasparov in 2000. It is worth learning because the endgame and the Anti-Berlin with 4.d3 are different plans. The lines cover the Berlin Wall, the Rio, and the quiet 4.d3 shells.",
  },
  {
    packId: "kings-indian-black",
    firstLineId: "kidb1",
    name: "King’s Indian Defence",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["d4", "Nf6", "c4", "g6"],
    tagline: "A fianchetto. A later central break.",
    lead: "The King's Indian is 1.d4 Nf6 2.c4 g6, with ...Bg7 and ...d6. Black fianchettoes, lets White build a centre, then strikes with ...e5 or ...c5.",
    rest: "It became a great fighting defence in the middle of the 20th century. It is worth learning because each White system has its own pawn structure. The lines cover the Classical, the Sämisch, the Four Pawns, the fianchetto, the Averbakh, and the Makogonov.",
  },
  {
    packId: "old-indian-black",
    firstLineId: "oib1",
    name: "Old Indian Defence",
    side: "b",
    lineCount: 9,
    line1Free: true,
    stem: ["d4", "d6", "c4", "Nf6"],
    tagline: "A flexible centre. No fianchetto required.",
    lead: "The Old Indian is 1.d4 d6 2.c4 Nf6, usually with ...Nbd7 and ...e5. Black holds a flexible centre without fianchettoing the king's bishop.",
    rest: "It is the older cousin of the King's Indian: the same central idea, with the bishop on e7 instead of g7. The lines cover Classical ...e5, the exchange on e5, a closed d5, the Bg5 pin, and the ...c6, ...c5, and ...e6 branches.",
  },
  {
    packId: "stafford-black",
    firstLineId: "stb1",
    name: "Stafford Gambit",
    side: "b",
    lineCount: 20,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6"],
    tagline: "A Petroff take. A concrete reply.",
    lead: "The Stafford Gambit is 1.e4 e5 2.Nf3 Nf6 3.Nxe5 Nc6. Black answers the capture on e5 with ...Nc6 instead of the quiet Petroff ...d6.",
    rest: "It is a sharp club line, and the pack already labels several of its branches as traps. It is worth the book move because the patterns are short and exact. The lines cover the main ...dxc6 shells, the declines, and those named trap lines.",
  },
  {
    packId: "ponziani-white",
    firstLineId: "pw1",
    name: "Ponziani Opening for White",
    side: "w",
    lineCount: 20,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nc6", "c3"],
    tagline: "Prepare d4. Meet each reply.",
    lead: "The Ponziani Opening is 1.e4 e5 2.Nf3 Nc6 3.c3. White prepares d4 and a classical pawn centre.",
    rest: "It is named after Domenico Lorenzo Ponziani, who analysed 3.c3 in the 18th century. It is less common than the Italian or the Ruy Lopez, so a prepared White can surprise people. The lines cover ...Nf6, ...d5, the countergambit, and the quieter bishop replies.",
  },
  {
    packId: "alekhine-black",
    firstLineId: "ab1",
    name: "Alekhine Defence",
    side: "b",
    lineCount: 18,
    line1Free: true,
    stem: ["e4", "Nf6"],
    tagline: "Invite the pawn pushes. Then chip away.",
    lead: "The Alekhine Defence is 1.e4 Nf6. Black invites White to push the e-pawn and take a large centre, then attacks that centre.",
    rest: "Alexander Alekhine used 1...Nf6 in the 1920s to show that a big pawn centre can become a target. It is worth learning because each White pawn wall has its own plan. The lines cover the Modern, the Exchange, the Four Pawns, the Two Pawns, and the quieter 2.Nc3.",
  },
  {
    packId: "french-black",
    firstLineId: "frb1",
    name: "French Defence for Black",
    side: "b",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "e6", "d4", "d5"],
    tagline: "A solid centre. A later ...c5 break.",
    lead: "The French Defence is 1.e4 e6 2.d4 d5. Black challenges the e-pawn at once and accepts a cramped light-squared bishop for a solid centre.",
    rest: "The name comes from a London versus Paris correspondence game in 1834. It is worth learning because the same two moves meet every main White system. The 10 lines are the Winawer, two Advance lines, two Tarrasch lines, the Classical, the Steinitz, the Exchange, the Rubinstein, and the King's Indian Attack.",
  },
  {
    packId: "ruy-lopez-white",
    firstLineId: "rlw1",
    name: "Ruy Lopez for White",
    side: "w",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "e5", "Nf3", "Nc6", "Bb5"],
    tagline: "Pressure on the knight. A long classical game.",
    lead: "The Ruy Lopez is 1.e4 e5 2.Nf3 Nc6 3.Bb5. White's bishop pressures the knight that defends the pawn on e5.",
    rest: "It is named after Ruy López de Segura, the 16th century Spanish priest who studied the opening in his book of 1561. It is worth learning because small differences in move order change the plan. The 10 lines cover the Closed Breyer, the Arkhangelsk, the Berlin, the Open Defence, the Exchange, the Schliemann, the Classical, the Old Steinitz, the Bird, and the Marshall.",
  },
  {
    packId: "sicilian-black",
    firstLineId: "sib1",
    name: "Sicilian for Black",
    side: "b",
    lineCount: 10,
    line1Free: true,
    stem: ["e4", "c5"],
    tagline: "Fight 1.e4 from the flank.",
    lead: "The Sicilian Defence is 1.e4 c5. Black answers the king's pawn from the flank and fights for the centre a move later.",
    rest: "It is one of the oldest replies to 1.e4, already analysed in the late 16th century, and it is the most common fighting defence today. The 10 lines cover the Najdorf, the Dragon, the Classical, the Sveshnikov, the Four Knights, the Alapin, the Smith-Morra, the Grand Prix, the Rossolimo, and the Closed Sicilian.",
  },
];
