import type { Lang } from "./i18n";

/** Feedback page and drill-pack request. English keys are the source strings. */
export const VOICE_COPY: Record<Lang, Record<string, string>> = {
  en: {
    "Request a drill pack": "Request a drill pack",
    "Suggested next drills": "Suggested next drills",
    "A short note for Opening Lab.": "A short note for Opening Lab.",
    "Name the opening you want next.": "Name the opening you want next.",
    "Thanks — we got it": "Thanks — we got it",
    "Your email, if you want a reply": "Your email, if you want a reply",
    "Opening name": "Opening name",
    Message: "Message",
    Send: "Send",
    "Sending…": "Sending…",
    "Could not send. Try again.": "Could not send. Try again.",
    "Your mail app should open so you can send it.":
      "Your mail app should open so you can send it.",
    "e.g. King's Indian for White": "e.g. King's Indian for White",
    "What should we know?": "What should we know?",
    "That email does not look right.": "That email does not look right.",
  },
  es: {
    "Request a drill pack": "Pedir un pack de ejercicios",
    "Suggested next drills": "Siguientes ejercicios",
    "A short note for Opening Lab.": "Una nota breve para Opening Lab.",
    "Name the opening you want next.": "Nombra la apertura que quieres a continuación.",
    "Thanks — we got it": "Gracias — lo recibimos",
    "Your email, if you want a reply": "Tu correo, si quieres respuesta",
    "Opening name": "Nombre de la apertura",
    Message: "Mensaje",
    Send: "Enviar",
    "Sending…": "Enviando…",
    "Could not send. Try again.": "No se pudo enviar. Inténtalo de nuevo.",
    "Your mail app should open so you can send it.":
      "Tu app de correo debería abrirse para enviarlo.",
    "e.g. King's Indian for White": "p. ej. King's Indian for White",
    "What should we know?": "¿Qué debemos saber?",
    "That email does not look right.": "Ese correo no parece correcto.",
  },
  zh: {
    "Request a drill pack": "申请一个训练包",
    "Suggested next drills": "建议的下一组训练",
    "A short note for Opening Lab.": "给 Opening Lab 留一句短话。",
    "Name the opening you want next.": "写下你希望接下来做的开局。",
    "Thanks — we got it": "谢谢 — 我们收到了",
    "Your email, if you want a reply": "留下邮箱，方便我们回复",
    "Opening name": "开局名称",
    Message: "留言",
    Send: "发送",
    "Sending…": "发送中…",
    "Could not send. Try again.": "没能发出。请再试一次。",
    "Your mail app should open so you can send it.": "邮件应用应会打开，以便你发送。",
    "e.g. King's Indian for White": "例如 King's Indian for White",
    "What should we know?": "我们该知道什么？",
    "That email does not look right.": "这个邮箱看起来不对。",
  },
  fr: {
    "Request a drill pack": "Demander un pack d'exercices",
    "Suggested next drills": "Prochains exercices suggérés",
    "A short note for Opening Lab.": "Une courte note pour Opening Lab.",
    "Name the opening you want next.": "Nomme l'ouverture que tu veux ensuite.",
    "Thanks — we got it": "Merci — c'est bien reçu",
    "Your email, if you want a reply": "Ton e-mail, si tu veux une réponse",
    "Opening name": "Nom de l'ouverture",
    Message: "Message",
    Send: "Envoyer",
    "Sending…": "Envoi…",
    "Could not send. Try again.": "Envoi impossible. Réessaie.",
    "Your mail app should open so you can send it.":
      "Ton appli mail devrait s'ouvrir pour l'envoyer.",
    "e.g. King's Indian for White": "p. ex. King's Indian for White",
    "What should we know?": "Que doit-on savoir ?",
    "That email does not look right.": "Cet e-mail ne semble pas correct.",
  },
  de: {
    "Request a drill pack": "Ein Übungspaket vorschlagen",
    "Suggested next drills": "Nächste Übungen",
    "A short note for Opening Lab.": "Eine kurze Nachricht an Opening Lab.",
    "Name the opening you want next.": "Nenne die Eröffnung, die als Nächstes kommen soll.",
    "Thanks — we got it": "Danke — ist angekommen",
    "Your email, if you want a reply": "Deine E-Mail, wenn du eine Antwort willst",
    "Opening name": "Name der Eröffnung",
    Message: "Nachricht",
    Send: "Senden",
    "Sending…": "Wird gesendet…",
    "Could not send. Try again.": "Konnte nicht senden. Versuch es noch einmal.",
    "Your mail app should open so you can send it.":
      "Deine Mail-App sollte sich öffnen, damit du es senden kannst.",
    "e.g. King's Indian for White": "z. B. King's Indian for White",
    "What should we know?": "Was sollen wir wissen?",
    "That email does not look right.": "Diese E-Mail sieht nicht richtig aus.",
  },
  pt: {
    "Request a drill pack": "Pedir um pacote de exercícios",
    "Suggested next drills": "Próximos exercícios",
    "A short note for Opening Lab.": "Uma nota curta para o Opening Lab.",
    "Name the opening you want next.": "Diz a abertura que queres a seguir.",
    "Thanks — we got it": "Obrigado — recebemos",
    "Your email, if you want a reply": "O teu email, se quiseres resposta",
    "Opening name": "Nome da abertura",
    Message: "Mensagem",
    Send: "Enviar",
    "Sending…": "A enviar…",
    "Could not send. Try again.": "Não foi possível enviar. Tenta outra vez.",
    "Your mail app should open so you can send it.":
      "A app de email deve abrir para o enviares.",
    "e.g. King's Indian for White": "ex.: King's Indian for White",
    "What should we know?": "O que devemos saber?",
    "That email does not look right.": "Esse email não parece certo.",
  },
  ru: {
    "Request a drill pack": "Запросить пакет упражнений",
    "Suggested next drills": "Следующие упражнения",
    "A short note for Opening Lab.": "Короткая заметка для Opening Lab.",
    "Name the opening you want next.": "Назови дебют, который нужен следующим.",
    "Thanks — we got it": "Спасибо — мы получили",
    "Your email, if you want a reply": "Почта, если нужен ответ",
    "Opening name": "Название дебюта",
    Message: "Сообщение",
    Send: "Отправить",
    "Sending…": "Отправка…",
    "Could not send. Try again.": "Не удалось отправить. Попробуйте ещё раз.",
    "Your mail app should open so you can send it.":
      "Почтовое приложение должно открыться, чтобы вы могли отправить.",
    "e.g. King's Indian for White": "напр. King's Indian for White",
    "What should we know?": "Что нам стоит знать?",
    "That email does not look right.": "Эта почта выглядит неверно.",
  },
  it: {
    "Request a drill pack": "Chiedi un pacchetto di esercizi",
    "Suggested next drills": "Prossimi esercizi",
    "A short note for Opening Lab.": "Una nota breve per Opening Lab.",
    "Name the opening you want next.": "Scrivi l'apertura che vuoi dopo.",
    "Thanks — we got it": "Grazie — ricevuto",
    "Your email, if you want a reply": "La tua email, se vuoi una risposta",
    "Opening name": "Nome dell'apertura",
    Message: "Messaggio",
    Send: "Invia",
    "Sending…": "Invio…",
    "Could not send. Try again.": "Invio non riuscito. Riprova.",
    "Your mail app should open so you can send it.":
      "L'app di posta dovrebbe aprirsi così puoi inviarlo.",
    "e.g. King's Indian for White": "es. King's Indian for White",
    "What should we know?": "Cosa dobbiamo sapere?",
    "That email does not look right.": "Quell'email non sembra giusta.",
  },
  hi: {
    "Request a drill pack": "ड्रिल पैक का अनुरोध",
    "Suggested next drills": "अगले सुझाए ड्रिल",
    "A short note for Opening Lab.": "Opening Lab के लिए एक छोटा संदेश।",
    "Name the opening you want next.": "जो ओपनिंग आगे चाहिए, उसका नाम लिखें।",
    "Thanks — we got it": "धन्यवाद — हमें मिल गया",
    "Your email, if you want a reply": "जवाब चाहिए तो अपना ईमेल",
    "Opening name": "ओपनिंग का नाम",
    Message: "संदेश",
    Send: "भेजें",
    "Sending…": "भेजा जा रहा है…",
    "Could not send. Try again.": "भेज नहीं सके। फिर कोशिश करें।",
    "Your mail app should open so you can send it.":
      "भेजने के लिए आपका मेल ऐप खुलना चाहिए।",
    "e.g. King's Indian for White": "उदा. King's Indian for White",
    "What should we know?": "हमें क्या जानना चाहिए?",
    "That email does not look right.": "वह ईमेल सही नहीं लग रहा।",
  },
  ja: {
    "Request a drill pack": "ドリルパックをリクエスト",
    "Suggested next drills": "次に欲しいドリル",
    "A short note for Opening Lab.": "Opening Lab への短いメッセージ。",
    "Name the opening you want next.": "次に欲しいオープニングの名前を書いてください。",
    "Thanks — we got it": "ありがとう — 受け取りました",
    "Your email, if you want a reply": "返信が必要ならメールアドレス",
    "Opening name": "オープニング名",
    Message: "メッセージ",
    Send: "送信",
    "Sending…": "送信中…",
    "Could not send. Try again.": "送れませんでした。もう一度。",
    "Your mail app should open so you can send it.":
      "送れるようにメールアプリが開くはずです。",
    "e.g. King's Indian for White": "例: King's Indian for White",
    "What should we know?": "何を伝えますか？",
    "That email does not look right.": "そのメールアドレスは正しくないようです。",
  },
  ar: {
    "Request a drill pack": "اطلب حزمة تمارين",
    "Suggested next drills": "التمارين التالية المقترحة",
    "A short note for Opening Lab.": "ملاحظة قصيرة لـ Opening Lab.",
    "Name the opening you want next.": "اكتب اسم الافتتاح الذي تريده تاليًا.",
    "Thanks — we got it": "شكرًا — وصلنا",
    "Your email, if you want a reply": "بريدك، إن أردت ردًا",
    "Opening name": "اسم الافتتاح",
    Message: "رسالة",
    Send: "إرسال",
    "Sending…": "جارٍ الإرسال…",
    "Could not send. Try again.": "تعذر الإرسال. حاول مرة أخرى.",
    "Your mail app should open so you can send it.":
      "يفترض أن يفتح تطبيق البريد لترسلها.",
    "e.g. King's Indian for White": "مثال: King's Indian for White",
    "What should we know?": "ماذا ينبغي أن نعرف؟",
    "That email does not look right.": "هذا البريد لا يبدو صحيحًا.",
  },
  tr: {
    "Request a drill pack": "Bir alıştırma paketi iste",
    "Suggested next drills": "Sonraki önerilen alıştırmalar",
    "A short note for Opening Lab.": "Opening Lab için kısa bir not.",
    "Name the opening you want next.": "Sırada istediğin açılışın adını yaz.",
    "Thanks — we got it": "Teşekkürler — aldık",
    "Your email, if you want a reply": "Yanıt istersen e-postan",
    "Opening name": "Açılış adı",
    Message: "Mesaj",
    Send: "Gönder",
    "Sending…": "Gönderiliyor…",
    "Could not send. Try again.": "Gönderilemedi. Yeniden dene.",
    "Your mail app should open so you can send it.":
      "Gönderebilmen için posta uygulaman açılmalı.",
    "e.g. King's Indian for White": "ör. King's Indian for White",
    "What should we know?": "Neyi bilmeliyiz?",
    "That email does not look right.": "Bu e-posta doğru görünmüyor.",
  },
};
