/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiPracticeReviewEvalRouteImport } from './routes/api/practice-review-eval'
import { Route as ApiUnlocksRouteImport } from './routes/api/unlocks'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account.delete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCheckoutSessionRouteImport } from './routes/api/checkout.session'
import { Route as ApiPlaySubscribeRouteImport } from './routes/api/play.subscribe'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiUnlocksClaimRouteImport } from './routes/api/unlocks.claim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPracticeReviewEvalRoute = ApiPracticeReviewEvalRouteImport.update({
  id: '/api/practice-review-eval',
  path: '/api/practice-review-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlocksRoute = ApiUnlocksRouteImport.update({
  id: '/api/unlocks',
  path: '/api/unlocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutSessionRoute = ApiCheckoutSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiCheckoutRoute,
} as any)
const ApiPlaySubscribeRoute = ApiPlaySubscribeRouteImport.update({
  id: '/api/play/subscribe',
  path: '/api/play/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlocksClaimRoute = ApiUnlocksClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ApiUnlocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/practice-review-eval': typeof ApiPracticeReviewEvalRoute
  '/api/unlocks': typeof ApiUnlocksRouteWithChildren
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/session': typeof ApiCheckoutSessionRoute
  '/api/play/subscribe': typeof ApiPlaySubscribeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/unlocks/claim': typeof ApiUnlocksClaimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/practice-review-eval': typeof ApiPracticeReviewEvalRoute
  '/api/unlocks': typeof ApiUnlocksRouteWithChildren
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/session': typeof ApiCheckoutSessionRoute
  '/api/play/subscribe': typeof ApiPlaySubscribeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/unlocks/claim': typeof ApiUnlocksClaimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/practice-review-eval': typeof ApiPracticeReviewEvalRoute
  '/api/unlocks': typeof ApiUnlocksRouteWithChildren
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/session': typeof ApiCheckoutSessionRoute
  '/api/play/subscribe': typeof ApiPlaySubscribeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/unlocks/claim': typeof ApiUnlocksClaimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/checkout'
    | '/api/feedback'
    | '/api/payments'
    | '/api/practice-review-eval'
    | '/api/unlocks'
    | '/api/account/delete'
    | '/api/auth/$'
    | '/api/checkout/session'
    | '/api/play/subscribe'
    | '/api/stripe/webhook'
    | '/api/unlocks/claim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/checkout'
    | '/api/feedback'
    | '/api/payments'
    | '/api/practice-review-eval'
    | '/api/unlocks'
    | '/api/account/delete'
    | '/api/auth/$'
    | '/api/checkout/session'
    | '/api/play/subscribe'
    | '/api/stripe/webhook'
    | '/api/unlocks/claim'
  id:
    | '__root__'
    | '/'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/checkout'
    | '/api/feedback'
    | '/api/payments'
    | '/api/practice-review-eval'
    | '/api/unlocks'
    | '/api/account/delete'
    | '/api/auth/$'
    | '/api/checkout/session'
    | '/api/play/subscribe'
    | '/api/stripe/webhook'
    | '/api/unlocks/claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRouteWithChildren
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiPracticeReviewEvalRoute: typeof ApiPracticeReviewEvalRoute
  ApiUnlocksRoute: typeof ApiUnlocksRouteWithChildren
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPlaySubscribeRoute: typeof ApiPlaySubscribeRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/practice-review-eval': {
      id: '/api/practice-review-eval'
      path: '/api/practice-review-eval'
      fullPath: '/api/practice-review-eval'
      preLoaderRoute: typeof ApiPracticeReviewEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlocks': {
      id: '/api/unlocks'
      path: '/api/unlocks'
      fullPath: '/api/unlocks'
      preLoaderRoute: typeof ApiUnlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/session': {
      id: '/api/checkout/session'
      path: '/session'
      fullPath: '/api/checkout/session'
      preLoaderRoute: typeof ApiCheckoutSessionRouteImport
      parentRoute: typeof ApiCheckoutRoute
    }
    '/api/play/subscribe': {
      id: '/api/play/subscribe'
      path: '/api/play/subscribe'
      fullPath: '/api/play/subscribe'
      preLoaderRoute: typeof ApiPlaySubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlocks/claim': {
      id: '/api/unlocks/claim'
      path: '/claim'
      fullPath: '/api/unlocks/claim'
      preLoaderRoute: typeof ApiUnlocksClaimRouteImport
      parentRoute: typeof ApiUnlocksRoute
    }
  }
}

interface ApiCheckoutRouteChildren {
  ApiCheckoutSessionRoute: typeof ApiCheckoutSessionRoute
}

const ApiCheckoutRouteChildren: ApiCheckoutRouteChildren = {
  ApiCheckoutSessionRoute: ApiCheckoutSessionRoute,
}

const ApiCheckoutRouteWithChildren = ApiCheckoutRoute._addFileChildren(
  ApiCheckoutRouteChildren,
)

interface ApiUnlocksRouteChildren {
  ApiUnlocksClaimRoute: typeof ApiUnlocksClaimRoute
}

const ApiUnlocksRouteChildren: ApiUnlocksRouteChildren = {
  ApiUnlocksClaimRoute: ApiUnlocksClaimRoute,
}

const ApiUnlocksRouteWithChildren = ApiUnlocksRoute._addFileChildren(
  ApiUnlocksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiCheckoutRoute: ApiCheckoutRouteWithChildren,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiPracticeReviewEvalRoute: ApiPracticeReviewEvalRoute,
  ApiUnlocksRoute: ApiUnlocksRouteWithChildren,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPlaySubscribeRoute: ApiPlaySubscribeRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
